Repository kalpavriksha-edu/kalpavriksha-academy, pull requests merged in 2023-10, with the labels that each got.

#17 Bugfix; Multiple db instance creation
  src/db/dbConnection.ts
  src/model/courseModel.ts
  src/server.ts
Labels: bug

#19 React-Typescript template application for Kalpavriksha Front-end Support
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: initial-commit

#21 Feature: Test Cases for Backend Course APIs
  package.json
  tests/controllers/controllers.js
  tests/controllers/courseController.test.ts
  tests/sample.test.js
  tests/services/courseService.test.ts
  tsconfig.json
Labels: enhancement

#24 Components for footer and navbar
  src/components/footer/footer.css
  src/components/footer/footer.tsx
  src/components/navbar/navbar.css
  src/components/navbar/navbar.tsx
Labels: enhancement
